### ISSUE TITLE
US01 - User registration

### ISSUE THREAD

**Issue by brendavsantos** [fga-eps-mds/2020.1-stay-safe-docs#102]
## Story Description
Me, as a user, would like to register in the application to have access to the occurrence registration functionality.

## Tasks
The following tasks must be completed for the story to be completed:       
- [x] [User CRUD - User](https://github.com/fga-eps-mds/2020.1-stay-safe-docs/issues/29)
- [x] [Registration screen - Frontend](https://github.com/fga-eps-mds/2020.1-stay-safe-front-end/issues/1)
- [x] [Integration of the registration screen - Frontend](https://github.com/fga-eps-mds/2020.1-stay-safe-front-end/issues/5)
