### ISSUE TITLE
US06 - View city statistics crimes

### ISSUE THREAD

**Issue by brendavsantos** [fga-eps-mds/2020.1-stay-safe-docs#107]
## Story Description
Me, as a user, would like to view crime statistics of a city to get a real sense of its security.

## Tasks
The following tasks must be completed for the story to be completed:
- [x] [Extraction SSP-DF - Secretary](https://github.com/fga-eps-mds/2020.1-stay-safe-secretary-service/issues/1) 
- [x] [Extraction SSP-SP - Secretary](https://github.com/fga-eps-mds/2020.1-stay-safe-secretary-service/issues/5)
- [x] [Endpoints to Get Data - Secretary](https://github.com/fga-eps-mds/2020.1-stay-safe-secretary-service/issues/9)
- [x] [Extract Population Data DF and SP - Secretary](https://github.com/fga-eps-mds/2020.1-stay-safe-secretary-service/issues/28)
- [x] [Screen to view statistics - Frontend](https://github.com/fga-eps-mds/2020.1-stay-safe-front-end/issues/43)
