### ISSUE TITLE
US10 - Evaluation Screen

### ISSUE THREAD

**Issue by brendavsantos** [fga-eps-mds/2020.1-stay-safe-docs#111]
## Story Description
Me, as a user, would like to rate a neighborhood in order to give my feedback on neighborhood safety and help other users.

## Tasks
The following tasks must be completed for the story to be completed:
- [x] [Rating CRUD - User](https://github.com/fga-eps-mds/2020.1-stay-safe-user-service/issues/7)
- [x] [Rating Endpoints - User](https://github.com/fga-eps-mds/2020.1-stay-safe-user-service/issues/14) 
- [x] [Average Rating Logic- User](https://github.com/fga-eps-mds/2020.1-stay-safe-user-service/issues/31)
- [x] [Evaluation screen - Frontend](https://github.com/fga-eps-mds/2020.1-stay-safe-front-end/issues/58)
