### ISSUE TITLE
US16 - Register an occurrence anonymously

### ISSUE THREAD

**Issue by brendavsantos** [fga-eps-mds/2020.1-stay-safe-docs#117]
## Story Description
Me, as a user, would like to register an occurrence(anonymously) in order to contribute to the safety of other users.

## Tasks
The following tasks must be completed for the story to be completed:
- [x] [Occurrence CRUD - User](https://github.com/fga-eps-mds/2020.1-stay-safe-user-service/issues/2)
- [x] [Integration with Google Maps API - Frontend](https://github.com/fga-eps-mds/2020.1-stay-safe-front-end/issues/3)
- [x] [Occurrences Endpoint - User](https://github.com/fga-eps-mds/2020.1-stay-safe-user-service/issues/14)
- [x] [Occurrence Registration Screen - Frontend](https://github.com/fga-eps-mds/2020.1-stay-safe-front-end/issues/9)
- [x] [Associate Occurrence to Location - Frontend](https://github.com/fga-eps-mds/2020.1-stay-safe-front-end/issues/21)
