### ISSUE TITLE
Backend and frontend environment setting

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-docs#34]
## Issue Description
Create the initial structure of Flask and Expo.

## Tasks:
- [x] Create dockerfile to Flask
- [x] Create Expo structure
- [x] Create dockerfile to Database (Postgres and Mongo)
