### ISSUE TITLE
Customize mkdocs

### ISSUE THREAD

**Issue by renan601** [fga-eps-mds/2020.1-stay-safe-docs#61]
## Issue Description
Customize Mkdocs to use Stay Safe branding and identify the team

## Tasks:
- [x] Customize the home page with project and team information
- [x] Customize tables and headers with Stay Safe colors
- [x] Add the Stay Safe logo
