### ISSUE TITLE
Update architecture document

### ISSUE THREAD

**Issue by silvasara** [fga-eps-mds/2020.1-stay-safe-docs#99]
## Issue Description
Update architecture document with new data model changes and update front-end modules.

## Tasks:
- [x] update front-end modules
- [x] update population data model
- [x] update rating table
- [x] update user table
- [x] place favorites table
- [x] update crime and occurrence names
